### ISSUE TITLE
3D version

### ISSUE THREAD

**Issue by MrNGS** [martemyev/specfem2vtu#1]
Dear @martemyev ,
I find this repo very helpful and, thank you for that.
 I was wondering how to extend it to the 3D case as the mesh generator, say, 
when using TETGEN instead of TRIANGLE? What should I be adding/modifying to interface tetgen for this?
Regards,
zaq

**Comment by martemyev** [comment]
Hi zaq,
I think converting specfem results in 3D may be prohibitively expensive for visualization from computational viewpoint. I would recommend visualizing a 3D solution in 2D planes/slices of interest - not in the whole 3D domain.
Best,
Mikhail

**Comment by MrNGS** [comment]
Hi and thank you much for the reply.
Point taken.  But just out of curiosity, are specfem generated matrices rather not so sparse?
Otherwise, I'd prefer stick with standard finite element world...

**Comment by martemyev** [comment]
Well, spectral FEM mass matrix is diagonal IIRC, which is very nice for solution of a wave equation, but this project specfem2vtu is for converting a specfem solution into VTU format for using in visualization tools like ParaView. Hence, it has little to do with sparsenness of matrices, and more with the grid and degrees of freedom of the spectral FEM - that is because this project takes an existing solution and simply converts it to a different format for visualization.

**Comment by MrNGS** [comment]
Thank you very much @martemyev for the answer.
I am closing this issue, and will sure come back when I have question(s) related to the incompressible repo.
Best regards.
zap
